#### general settings
name: hc18_kernel_noise
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [4]

#### datasets
datasets:
  train:
    name: hc18_train
    mode: LQGT
    aug: noise
    noise_data: ../datasets/hc18/hc18_noise/
    dataroot_GT: ../datasets/hc18/generated/clean/train_tdsr/HR
    dataroot_LQ: ../datasets/hc18/generated/clean/train_tdsr/LR

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 64
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: hc18_validation
    mode: LQGT
    aug: noise
    noise_data: ../datasets/hc18/hc18_noise_val/
    dataroot_GT: ../datasets/hc18/generated/clean/val_tdsr/HR
    dataroot_LQ: ../datasets/hc18/generated/clean/val_tdsr/LR

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: NLayerDiscriminator
  in_nc: 3
  nf: 64
  nlayer: 3

#### path
path:
  pretrain_model_G: ./pretrained_model/RRDB_PSNR_x4.pth
  strict_load: true
  resume_state: 

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999
  lr_scheme: MultiStepLR

  niter: 160001 #60001 valore numero iterazioni originale
  warmup_iter: -1  # no warm up
  lr_steps: [20000, 40000, 80000, 120000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 1e3

#### logger
logger:
  print_freq: 16
  save_checkpoint_freq: !!float 3e3
